#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${XO_ROOT_DIR:-$(pwd)}"
ENV_FILE="${ROOT_DIR}/.env"
ENV_LOCAL="${ROOT_DIR}/.env.local"
FORCE="${FORCE:-false}"

if [[ -s "${ENV_LOCAL}" && "${FORCE}" != "1" && "${FORCE}" != "true" ]]; then
  printf "[instance] %s already exists and is not empty.\n" "${ENV_LOCAL}" >&2
  printf "[instance] Run 'make instance.init FORCE=1' to overwrite it.\n" >&2
  exit 1
fi

# Base name comes from the tracked .env (never from the environment — a FORCE
# re-run would otherwise pick up the already-suffixed name from .env.local).
BASE_NAME="$(sed -n 's/^XO_PROJECT_NAME=//p' "${ENV_FILE}" 2>/dev/null | tail -1 | tr -d '"')"
BASE_NAME="${BASE_NAME:-dev-setup}"

INSTANCE="${INSTANCE:-$(basename "${ROOT_DIR}")}"
INSTANCE="$(printf '%s' "${INSTANCE}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g; s/^-+//; s/-+$//')"
if [[ -z "${INSTANCE}" ]]; then
  printf "[instance] Could not derive an instance name from %s — pass INSTANCE=<name>.\n" "${ROOT_DIR}" >&2
  exit 1
fi
PROJECT_NAME="${BASE_NAME}-${INSTANCE}"

# Ports already taken: host listeners plus the bindings of all containers,
# including stopped ones (they will claim their ports again on start).
USED_PORTS="$(
  {
    lsof -nP -iTCP -sTCP:LISTEN 2>/dev/null | awk 'NR>1 {sub(/.*:/, "", $9); print $9}'
    docker ps -aq 2>/dev/null | xargs -r docker inspect \
      --format '{{range $p, $b := .HostConfig.PortBindings}}{{range $b}}{{.HostPort}}{{"\n"}}{{end}}{{end}}' 2>/dev/null
  } | grep -E '^[0-9]+$' | sort -un
)" || true

# Deterministic per-checkout offset (1..200) keeps two initialized checkouts
# apart and always lands above the plain defaults of an un-initialized checkout.
OFFSET=$(( $(printf '%s' "${ROOT_DIR}" | cksum | cut -d' ' -f1) % 200 + 1 ))

PICKED_PORTS=""
pick_port() {
  local candidate=$(( $1 + OFFSET ))
  while grep -qx "${candidate}" <<< "${USED_PORTS}" || grep -qx "${candidate}" <<< "${PICKED_PORTS}"; do
    candidate=$(( candidate + 1 ))
  done
  PICKED_PORTS+="${candidate}"$'\n'
  printf '%s' "${candidate}"
}

# php uses unprivileged bases so secondary instances never need root ports.
PHP_PORT="$(pick_port 8080)"
PHP_TLS_PORT="$(pick_port 8443)"
NODE_PORT="$(pick_port 4200)"
POSTGRES_PORT="$(pick_port 5432)"
REDIS_PORT="$(pick_port 6379)"
LOCALSTACK_PORT_HOST="$(pick_port 4566)"
MAILPIT_SMTP_PORT="$(pick_port 1025)"
MAILPIT_UI_PORT="$(pick_port 8025)"
RABBITMQ_PORT="$(pick_port 5672)"
RABBITMQ_MGMT_PORT="$(pick_port 15672)"

TMP_ENV_LOCAL="$(mktemp)"
trap 'rm -f "${TMP_ENV_LOCAL}"' EXIT

cat > "${TMP_ENV_LOCAL}" <<EOF
# Generated by 'make instance.init' — per-instance overrides, gitignored.
# Regenerate with 'make instance.init FORCE=1'.
XO_PROJECT_NAME=${PROJECT_NAME}
XO_PHP_PORT=${PHP_PORT}
XO_PHP_TLS_PORT=${PHP_TLS_PORT}
XO_NODE_PORT=${NODE_PORT}
XO_POSTGRES_PORT=${POSTGRES_PORT}
XO_REDIS_PORT=${REDIS_PORT}
XO_LOCALSTACK_PORT=${LOCALSTACK_PORT_HOST}
XO_MAILPIT_SMTP_PORT=${MAILPIT_SMTP_PORT}
XO_MAILPIT_UI_PORT=${MAILPIT_UI_PORT}
XO_RABBITMQ_PORT=${RABBITMQ_PORT}
RABBITMQ_MANAGEMENT_PORT=${RABBITMQ_MGMT_PORT}
EOF

# App-level URLs are only overridden when the project actually defines them.
if grep -q '^FRONTEND_URL=' "${ENV_FILE}" 2>/dev/null; then
  printf 'FRONTEND_URL=https://localhost:%s\n' "${NODE_PORT}" >> "${TMP_ENV_LOCAL}"
fi
if grep -q '^VITE_API_BASE_URL=' "${ENV_FILE}" 2>/dev/null; then
  printf 'VITE_API_BASE_URL="https://localhost:%s/api"\n' "${PHP_TLS_PORT}" >> "${TMP_ENV_LOCAL}"
fi

mv "${TMP_ENV_LOCAL}" "${ENV_LOCAL}"
trap - EXIT

printf "[instance] Wrote %s\n" "${ENV_LOCAL}"
printf "[instance] Project name:      %s\n" "${PROJECT_NAME}"
printf "[instance] Frontend (vite):   https://localhost:%s\n" "${NODE_PORT}"
printf "[instance] API (https/http):  https://localhost:%s / http://localhost:%s\n" "${PHP_TLS_PORT}" "${PHP_PORT}"
printf "[instance] Postgres:          localhost:%s\n" "${POSTGRES_PORT}"
printf "[instance] Redis:             localhost:%s\n" "${REDIS_PORT}"
printf "[instance] Localstack:        localhost:%s\n" "${LOCALSTACK_PORT_HOST}"
printf "[instance] Mailpit (smtp/ui): localhost:%s / http://localhost:%s\n" "${MAILPIT_SMTP_PORT}" "${MAILPIT_UI_PORT}"
printf "[instance] RabbitMQ (amqp/ui):localhost:%s / http://localhost:%s\n" "${RABBITMQ_PORT}" "${RABBITMQ_MGMT_PORT}"
printf "[instance] Next: make start && make init\n"
